### ISSUE TITLE
Code Review- 26576794

### ISSUE THREAD

**Issue by Ellis2657** [JosiahCarr/CMP1903M-A01-2223#3]
What you have done well: 
The code you have here is commented very well, but there are still some sections that could be commented.
You have got most things needed working in this code piece, but you are missing any form of error handling (such as an invalid input if the user selects a shuffle type). 
Another thing I want to bring up is that you need to do more work on the output system. Your outputs are all combined together and its hard to tell which shuffle is which as there is no clear designation. You could definitely make the outputs more readable. Looking through the code, you should also add a test for the other forms of shuffling - (No shuffle and the Fisher-yates shuffle).
Overall I believe your code is formed fairly well but I would suggest you improve and work on the outputs and their values a lot more

**Comment by JosiahCarr** [comment]
Thanks very much for bringing up these issues for improvement.
I will add/change the following:

- Error handling, including exceptions
- More comments
- More organised and legible output messages
